blank_issues_enabled: false
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/TreasureProject/treasure-marketplace/discussions
    about: Please ask and answer questions here.
  - name: Treasure DAO Chat
    url: https://discord.gg/treasuredao
    about: A dedicated discord server hosted by Treasure DAO
